/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-02 14:01:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.text.SimpleDateFormat;

public final class HelloJSP_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


public int add(int num1, int num2) {
	return num1 + num2 ;
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/IncludeFile.jsp", Long.valueOf(1651491975473L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"IsErrorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	Date date = new Date();
	SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
	String today = dateFormat.format(date);
	LocalDate yesterday = LocalDate.now().minusDays(1);
	LocalDateTime tomorrow = LocalDateTime.now().plusDays(1);

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>HelloJSP</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h2>JSP Test</h2>\r\n");
      out.write("	<div>\r\n");
      out.write("		<h3>0. 테스트</h3>\r\n");
      out.write("		<p>\r\n");
      out.write("			");

				out.println("오늘 날짜 : " + today);
				out.println("<br>");
				out.println("어제 날짜 : " + yesterday);
				out.println("<br>");
				out.println("내일 날짜 : " + tomorrow);
			
      out.write("<br>\r\n");
      out.write("			덧셈 결과 : ");
      out.print( add(10, 20) );
      out.write("</p>\r\n");
      out.write("		<h3>1. 클라이언트와 서버의 환경정보 읽기</h3>\r\n");
      out.write("		<a href=\"RequestWebInfo.jsp?id=qqwwee41&password=aassdd41\">GET 방식 전송</a> <br>\r\n");
      out.write("		<form action=\"RequestWebInfo.jsp\" method=\"post\">\r\n");
      out.write("			ID : <input type=\"text\" name=\"id\" value=\"qqwwee41\"> <br>\r\n");
      out.write("			PASSWORD : <input type=\"text\" name=\"password\" value=\"aassdd41\"> <br>\r\n");
      out.write("			<input type=\"submit\" value=\"POST 방식 전송\">\r\n");
      out.write("		</form>\r\n");
      out.write("		<h3>2. 클라이언트의 요청 매개변수 읽기</h3>\r\n");
      out.write("		<form action=\"RequestParameter.jsp\" method=\"post\">\r\n");
      out.write("			아이디 : <input type=\"text\" name=\"id\" value=\"\"> <br>\r\n");
      out.write("			성별 : \r\n");
      out.write("			<input type=\"radio\" name=\"gender\" value=\"man\">남자\r\n");
      out.write("			<input type=\"radio\" name=\"gender\" value=\"woman\">여자 <br>\r\n");
      out.write("			관심사항 :\r\n");
      out.write("			<input type=\"checkbox\" name=\"favo\" value=\"eco\">경제\r\n");
      out.write("			<input type=\"checkbox\" name=\"favo\" value=\"pol\">정치\r\n");
      out.write("			<input type=\"checkbox\" name=\"favo\" value=\"ent\">연예 <br>\r\n");
      out.write("			자기소개 :\r\n");
      out.write("			<textarea name=\"intro\" cols=\"30\" rows=\"4\"></textarea> <br>\r\n");
      out.write("			<input type=\"submit\" value=\"전송하기\">\r\n");
      out.write("		</form>\r\n");
      out.write("		<h3>3. HTTP 요청 헤더 정보 읽기</h3>\r\n");
      out.write("		<a href=\"RequestHeader.jsp\">요청 헤더 정보 읽기</a>\r\n");
      out.write("		\r\n");
      out.write("		<hr>\r\n");
      out.write("		\r\n");
      out.write("		<h2>1. 로그인 폼</h2>\r\n");
      out.write("		");

		String loginErr = request.getParameter("loginErr");
		if (loginErr != null) out.print("로그인 실패");
		
      out.write("<form action=\"ResponseLogin.jsp\" method=\"post\">\r\n");
      out.write("			아이디 : <input type=\"text\" name=\"user_id\" placeholder=\"아이디를 입력하세요.\"> <br>\r\n");
      out.write("			패스워드 : <input type=\"password\" name=\"user_pwd\" placeholder=\"비밀번호를 입력하세요.\"> <br>\r\n");
      out.write("			<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("		</form>\r\n");
      out.write("		<h2>2. HTTP 응답 헤더 설정하기</h2>\r\n");
      out.write("		<form action=\"ResponseHeader.jsp\" method=\"get\">\r\n");
      out.write("			날짜 형식 : <input type=\"text\" name=\"add_date\" value=\"2022-05-02\"> <br>\r\n");
      out.write("			숫자 형식 : <input type=\"text\" name=\"add_int\" value=\"8282\"> <br>\r\n");
      out.write("			문자 형식 : <input type=\"text\" name=\"add_str\" value=\"가나다\"> <br>\r\n");
      out.write("			<input type=\"submit\" value=\"응답 헤더 설정 & 출력\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
